// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA70ecOLnc5CuOYcezSKQpKuEVeWfAb8w4',
    appId: '1:609299836964:android:f2f6e893b4dad3c73068b1',
    messagingSenderId: '609299836964',
    projectId: 'shopzen-42af3',
    storageBucket: 'shopzen-42af3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2qUU5QhhBghzWCoKJLEB4PKjPArD6no',
    appId: '1:609299836964:ios:55e3e78cb3e4d4e53068b1',
    messagingSenderId: '609299836964',
    projectId: 'shopzen-42af3',
    storageBucket: 'shopzen-42af3.firebasestorage.app',
    androidClientId: '609299836964-7pdmjjsc26hje9388lf7eqoup33a5m9s.apps.googleusercontent.com',
    iosClientId: '609299836964-oiu82rgsdb7te5s7v1p0sol0f4cof7p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopZen',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjEXw_lZoMGtAvYSBlhPwDxfRD29Pb_ms',
    appId: '1:609299836964:web:c0a282d7ab96e7a53068b1',
    messagingSenderId: '609299836964',
    projectId: 'shopzen-42af3',
    authDomain: 'shopzen-42af3.firebaseapp.com',
    storageBucket: 'shopzen-42af3.firebasestorage.app',
    measurementId: 'G-5X0XJ8D69N',
  );

}