enum NotificationsType {
  normal,
  adminMessage,
  newMessage,
  newFollower,
  newComment,
  newLike,
  newPost,
  newFollowerRequest,
  newFollowerRequestAccepted,
  newFollowerRequestRejected,
  newFollowerRequestCancelled,
  newFollowerRequestExpired,
  newOrder,
}
